### ISSUE TITLE
Does not install on Julia 1.4

### ISSUE THREAD

**Issue by tallakt** [simonschoelly/KittyTerminalImages.jl#1]
```
(@v1.4) pkg> add "https://github.com/simonschoelly/KittyTerminalImages.jl"
   Updating git-repo `https://github.com/simonschoelly/KittyTerminalImages.jl`
ERROR: could not find project file in package at https://github.com/simonschoelly/KittyTerminalImages.jl
```

On MacOS

**Comment by simonschoelly** [comment]
Hi, thanks for creating that issue, unfortunately I some how missed the notification.

I added now a Project.toml file that makes it work on Julia 1.4. But as a lot of time has past, I probably want to do verify that everything works correctly (so far it seems to work on my linux machine) and maybe also do some refactoring before I add this to the general registry.

Until then, you can manually check out the package by writing `]add https://github.com/simonschoelly/KittyTerminalImages.jl` in your Julia repl. Let me know if there are issues on MacOS.

**Comment by tallakt** [comment]
This works on my machine
