### ISSUE TITLE
Kitty holds on to USB disk

### ISSUE THREAD

**Issue by tallakt** [simonschoelly/KittyTerminalImages.jl#3]
I loaded some data using `CSV` from an usb SD card, and then after using `cd` to another drive I am still not able to eject the SD card. OSX says: "The disk __ couldn't be ejected because "kitty" is using it."

**Comment by simonschoelly** [comment]
Are you sure that the problem is with `KittyTerminalImages`? For me it looks more like you did not close the csv file and now OSX thinks its the kitty terminal that holds the file open, while it is the process running inside it.

**Comment by tallakt** [comment]
True. Could probably be the CSV package or just Julia
